version: 2.1
jobs:
  build:
    docker: 
      - image: gitpitch/ci:latest
        auth:
            username: davidmrussell
            password: $TEST_DOCKERHUB_PASSWORD
    shell: /bin/sh -leo pipefail
    environment:
      - BASH_ENV: /etc/profile
    steps:
      - checkout
      - run:
          name: "echo GITPITCH_CI_TARGET"
          command: |
              echo $GITPITCH_CI_TARGET
      - run:
          name: "echo GITPITCH_CI_TYPE"
          command: |
              echo $GITPITCH_CI_TYPE
      - run:
          name: "echo GITPITCH_CI_AGENTS"
          command: |
              echo $GITPITCH_CI_AGENTS
      - run: /gitpitchci/start.sh $GITPITCH_CI_TARGET $GITPITCH_CI_TYPE $GITPITCH_CI_AGENTS
      - store_artifacts:
          path: /gitpitch/artifacts
      - persist_to_workspace:
          root: /gitpitch
          paths:
              artifacts
