version: 2.1
jobs:
  build:
    docker: 
      - image: gitpitch/ci:latest
        auth:
          username: davidmrussell
          password: $TEST_DOCKERHUB_PASSWORD
    shell: /bin/sh -leo pipefail
    environment:
      - BASH_ENV: /etc/profile
    working_directory: /repo
    steps:
      - checkout
      - run: echo $GITPITCH_CI_GEN_TARGET
      - run: echo $BASH_ENV
      - run: cat $BASH_ENV
      - run: source $BASH_ENV
      - run: echo $GITPITCH_CI_GEN_TARGET
      - run: /gitpitchci/start.sh
      - store_artifacts:
          path: /gitpitch/artifacts
      - persist_to_workspace:
          root: /gitpitch
          paths:
              artifacts
