version: 2.1
jobs:
  build:
    docker: 
      - image: gitpitch/ci:latest
        auth:
          username: davidmrussell
          password: $TEST_DOCKERHUB_PASSWORD
    working_directory: /repo
    steps:
      - checkout
      - run: /gitpitchci/start.sh
      - persist_to_workspace:
        root: /gitpitch
        paths:
          - artifacts
      - store_artifacts:
        path: /gitpitch/artifacts
